services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=graphql-poc'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=graphql-poc'
    ports:
      - '5432:5432'
    volumes:
      - ./dummy-data.sql:/docker-entrypoint-initdb.d/dummy-data.sql
